### ISSUE TITLE
Incorrect Willpower displayed

### ISSUE THREAD

**Issue by wastevens** [gnu-lorien/twistedvines#12]
When view Che to print (http://twistedvines.parseapp.com/#character/nWlajZHnX2/print) he is displayed as having 7 Willpower instead of 6.  While I appreciate that, it ain't right. :)

**Comment by gnu-lorien** [comment]
Moving this out one milestone. The reason it displays as 7 is because that's the max you **can** have and there was no other way in this system currently to represent that on a printable sheet.
