### ISSUE TITLE
Earned total at the top of the XP page doesn't update as earned changes dynamically

### ISSUE THREAD

**Issue by wirelesshnic** [gnu-lorien/twistedvines#8]
I gave myself a lot of XP but it does not calculate in the earned field.  Furthermore, the spent field is not calculating any of my expenditures.
![xp cal](https://cloud.githubusercontent.com/assets/16339761/11877316/94938f14-a4bc-11e5-8d55-ef805405e6b4.JPG)

**Comment by gnu-lorien** [comment]
Earned field in the header doesn't update. Got it.

The spent field currently won't include anything you bought, but the history view will. This part falls into "Enhancement" as that integration was the task I decided to stop waiting to finish before showing this to people.

**Comment by gnu-lorien** [comment]
This bug is super strange. I could get it to happen every time for a few minutes and now I can't get it to happen at all. I'm guessing that makes this somehow related to the "fake" experience notation that comes from character creation.

**Comment by gnu-lorien** [comment]
Turns out this bug had everything to do with not properly reflowing when removing experience. I did a bunch of work to fix this.
